/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infra;


import java.awt.Color;
import java.awt.Component;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author jhonson
 */
public class Interfaz_Dispache extends javax.swing.JFrame implements Runnable{
    int IdContador=0;
    Queue<Proceso> Ready = new LinkedList<>();
    Queue<Proceso> Block = new LinkedList<>();
    Thread temporizador;
    Thread temporizador2;
    DefaultListModel modeloExit = new DefaultListModel();
    boolean Recursos = true;
    Proceso Temp=null;
    
    

    /**
     * Creates new form Interfaz_Dispache
     */
    public Interfaz_Dispache() {
        temporizador = new Thread(this);
        temporizador.start();
        temporizador2 = new Thread(this);
        temporizador2.start();
        initComponents();
        jPanel1.setBackground(Color.GREEN);
        
        DefaultListModel modelo = new DefaultListModel();
        modelo.addElement("Proceso Infinito");
        modelo.addElement("Proceso Bloqueo");
        modelo.addElement("Proceso Termina");
        jList5.setModel(modelo);
        jList5.setCellRenderer( new MyListRenderer2());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("NEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Ready");

        jLabel2.setText("Running");

        jLabel3.setText("Dispache:");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jLabel4.setText("Block");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"CPU Libre"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList3);

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList4);

        jLabel6.setText("Exit");

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        jLabel7.setText("Recursos disponibles:");

        jLabel9.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setText("Sin procesos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel9)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(67, 67, 67))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(263, 263, 263))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(52, 52, 52))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jButton1))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Proceso P = new Proceso();
        
        switch (jList5.getSelectedIndex()) {
            case 0:
                P.ID=IdContador;
                P.Tipo="Infinito";
                P.Nombre="Proceso "+IdContador;
                P.Dato=0;
                P.Resultado=0;
                P.Duracion=1000;
                P.sumatoria= 1;
                P.tiemporestante=1000;
                P.Estado="Ready";
                P.Bloqueo=false;
                Ready.add(P);
                IdContador+=1;
                ListaReady();
                break;
            case 1:
                P.ID=IdContador;
                P.Tipo="Bloqueo";
                P.Nombre="Proceso "+IdContador;
                P.Dato=0;
                P.Resultado=0;
                P.Duracion=15;
                P.sumatoria= 10;
                P.tiemporestante=15;
                P.Estado="Ready";
                P.Bloqueo=true;
                IdContador+=1;
                Ready.add(P);
                ListaReady();
                break;
            case 2:
                P.ID=IdContador;
                P.Tipo="Termina";
                P.Nombre="Proceso "+IdContador;
                P.Dato=0;
                P.Resultado=0;
                P.Duracion=10;
                P.sumatoria= 5;
                P.tiemporestante=10;
                P.Estado="Ready";
                P.Bloqueo=false;
                Ready.add(P);
                IdContador+=1;
                ListaReady();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    void ListaReady(){
        try{
        DefaultListModel modelo = new DefaultListModel();
        Object[] list = Ready.toArray();
        
        for(int i = 0; i<=list.length-1; i++){
            modelo.addElement("Proceso "+ ((Proceso)list[i]).ID);
        }
        jList1.setModel(modelo);
        jList1.setCellRenderer( new MyListRenderer1(list));
        }catch(java.lang.NullPointerException e){}
    }
    void ListaExit(Proceso P){
        modeloExit.addElement("Proceso "+ P.ID);
        jList4.setModel(modeloExit);
        
    }
    
    void ListaBlock(){
        try{ 
        DefaultListModel modelo = new DefaultListModel();
        Object[] list = Block.toArray();
        
        for(int i = 0; i<=list.length-1; i++){
            modelo.addElement("Proceso "+ ((Proceso)list[i]).ID);
        }
        jList2.setModel(modelo);
        jList2.setForeground(Color.red);
        }catch(java.lang.NullPointerException e){}
    }
    
    void ListaRunning(Proceso P){
        DefaultListModel modelo = new DefaultListModel();
        modelo.addElement("Id: "+ P.ID);
        modelo.addElement("Tipo: "+ P.Tipo);
        modelo.addElement("Duracion: "+ P.Duracion+"s");
        modelo.addElement("Sumatoria: "+ P.sumatoria);
        modelo.addElement("Tiempo restante: "+ P.tiemporestante +"s");
        modelo.addElement("Resultado Sumatoria: "+ P.Resultado);
        modelo.addElement("Utiliza Recuros: "+ P.Utilizando_Recurso);
        
        if(null != P.Tipo)switch (P.Tipo) {
            case "Infinito":
                jList3.setBackground(Color.GREEN);
                break;
            case "Bloqueo":
                jList3.setBackground(Color.RED);
                break;
            default:
                jList3.setBackground(Color.BLUE);
                break;
        }
        
        jList3.setModel(modelo);
    }

    void CPULibre(){
        DefaultListModel modelo = new DefaultListModel();
        modelo.addElement("CPU libre");
        jList3.setModel(modelo);
        jLabel8.setText("Sin procesos");
        jList3.setBackground(Color.WHITE);
    }
    
    
    public void run() {
        run2();
        
        Thread ct = Thread.currentThread();
        while(ct == temporizador) {  
            Runing();
        try {
                Thread.sleep(1000*5);
                }catch(InterruptedException e) {}
        }
    }

    public void run2() {
        int segundos=0;
        Thread ct2 = Thread.currentThread();
        while(ct2 == temporizador2) {
            if(segundos==5){
                jLabel9.setText(Integer.toString(segundos));
                segundos=0;
            }
            try{
                jLabel9.setText(Integer.toString(segundos++));
            }catch(java.lang.NullPointerException e){}
        try {
                Thread.sleep(1000);
                }catch(InterruptedException e) {}
        }
    }
    void Runing(){
        
            try{
                CPULibre();
            }catch(java.lang.NullPointerException e){}
            
            if(!Block.isEmpty()){
                ListaBlock();
            }
            
            if(!Ready.isEmpty()){
                ListaReady();
            }
            
            
            if(Temp!=null){
                if(Temp.Bloqueo){
                    Recursos=true;
                    jPanel1.setBackground(Color.GREEN);
                }
                ListaExit(Temp);
                Temp=null;
            }
            
            if(!Ready.isEmpty() || !Block.isEmpty()){
                
                if(Recursos==false && Ready.peek().Bloqueo==true && Ready.peek().Utilizando_Recurso==false){
                    Block.add(Ready.poll());
                    ListaBlock();
                    Runing();
                    return;
                }
                
                Proceso P;
                
                if(!Block.isEmpty() && Recursos==true){
                    P =Block.poll();
                    Recursos=false;
                    jPanel1.setBackground(Color.RED);
                } 
                else{P= Ready.poll();}
                
                
                jLabel8.setText("Se sedio el control al Proceso "+P.ID);
                P.Resultado+=P.sumatoria;
                P.tiemporestante-=5;
                ListaReady();
                ListaBlock();
                ListaRunning(P);
                
                if(P.tiemporestante<=0){
                    Temp=P;
                }
                else{
                    
                    if(P.Bloqueo){
                        Recursos=false;
                        jPanel1.setBackground(Color.RED);
                        P.Utilizando_Recurso=true;
                    }
                    Ready.add(P);}
            }
    }
    
    class MyListRenderer1 extends DefaultListCellRenderer
    {   
        Object[] list;
        public MyListRenderer1(Object[] list){
            this.list=list;
        }
        
        public String Encontrar(String S){
            for(int i = 0; i<list.length; i++){
                if(S == null ? ((Proceso)list[i]).Nombre == null : S.equals(((Proceso)list[i]).Nombre)){
                    return ((Proceso)list[i]).Tipo;
                }
            }
            return null;
        }
  
        public Component getListCellRendererComponent( JList list,
                Object value, int index, boolean isSelected,
                boolean cellHasFocus )
        {
            super.getListCellRendererComponent( list, value, index,
                    isSelected, cellHasFocus );
  
            
            //System.out.print(value.toString());
            
            if(null != Encontrar(value.toString()))
            switch (Encontrar(value.toString())) {
                case "Infinito":
                    setForeground( Color.GREEN );
                    break;
                case "Bloqueo":
                    setForeground( Color.RED );
                    break;
                default:
                    setForeground( Color.BLUE );
                    break;
            }
            return(this);
        }
    }
    
    class MyListRenderer2 extends DefaultListCellRenderer
    {   
        
        public Component getListCellRendererComponent( JList list,
                Object value, int index, boolean isSelected,
                boolean cellHasFocus )
        {
            super.getListCellRendererComponent( list, value, index,
                    isSelected, cellHasFocus );
  
            
            //System.out.print(value.toString());
            
            
            switch (value.toString()) {
                case "Proceso Infinito":
                    setForeground( Color.GREEN );
                    break;
                case "Proceso Bloqueo":
                    setForeground( Color.RED );
                    break;
                default:
                    setForeground( Color.BLUE );
                    break;
            }
            return(this);
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Dispache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Dispache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Dispache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Dispache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Dispache().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
